package com.takeaway.takeaway.dataaccess.model.enums;

public enum ActionTypes {
    AUTH_CHANGE_PASSWORD("AUTH_CHANGE_PASSWORD"),
    USER_DELETE_PROFILE_PICTURE("USER_DELETE_PROFILE_PICTURE"),
    USER_UPDATE_PROFILE_PICTURE("USER_UPDATE_PROFILE_PICTURE"),
    USER_UPDATE_BASIC_INFO("USER_UPDATE_BASIC_INFO"),
    USER_UPDATE_USERNAME("USER_UPDATE_USERNAME"),
    USER_UPDATE_EMAIL("USER_UPDATE_EMAIL"),
    USER_MODIFY_ADDRESS("USER_MODIFY_ADDRESS"),
    ITEM_CREATE("ITEM_CREATE"),
    ITEM_UPDATE("ITEM_UPDATE"),
    ITEM_DELETE("ITEM_DELETE"),
    ITEM_SET_PUBLISH_STATE("ITEM_SET_PUBLISH_STATE"),
    ITEM_CHANGE_PICTURE_ORDER("ITEM_CHANGE_PICTURE_ORDER"),
    ITEM_ADD_PICTURE("ITEM_ADD_PICTURE"),
    ITEM_DELETE_PICTURE("ITEM_DELETE_PICTURE"),
    ITEM_REPORT("ITEM_REPORT");

    private String inText;

    ActionTypes(String inText) {
        this.inText = inText;
    }

    @Override
    public String toString() {
        return inText;
    }
}
